linters:
  enable-all: true
  disable:
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

    # misc
    - depguard
    - godox
    - dupl
    - dogsled
linters-settings:
  revive:
    rules:
      - name: unexported-return
        disabled: true
